<?php

namespace TrackBundle\Repository;

/**
 * ProductTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
