<?php

namespace TrackBundle\Repository;

/**
 * ProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
