<?php

namespace TrackBundle\Repository;

/**
 * ProductStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
