<?php

namespace TrackBundle\Repository;

/**
 * ProductAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
