<?php

/*
 * Nexxus Stock Keeping (online voorraad beheer software)
 * Copyright (C) 2018 Copiatek Scan & Computer Solution BV
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see licenses.
 *
 * Copiatek – info@copiatek.nl – Postbus 547 2501 CM Den Haag
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Supplier;
use AppBundle\Entity\User;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function findMine(User $user)
    {
        if ($user->hasRole("ROLE_LOCAL") || $user->hasRole("ROLE_LOGISTICS"))
            return $this->findBy(array("location" => $user->getLocationIds()), array('id' => 'DESC'));
        else
            return $this->findBy(array(), array('id' => 'DESC'));
    }


    /**
     * This function searches in fields: Id, Kvk, Email, Name
     */
    public function findBySearchQuery(\AppBundle\Helper\IndexSearchContainer $search)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->from("AppBundle:Supplier", "o")->select("o")->orderBy("o.id", "DESC");

        if ($search->query)
        {
            if (is_numeric($search->query))
            {
                $qb = $qb->andWhere("o.id = :query OR o.kvkNr = :query OR o.name LIKE :queryLike");
            }
            else
            {
                $qb = $qb->andWhere("o.email = :query OR o.name LIKE :queryLike");
            }

            $qb = $qb->setParameter("query", $search->query)->setParameter("queryLike", '%'.$search->query.'%');
        }

        if ($search->location)
            $qb = $qb->andWhere("o.location = :location")->setParameter("location", $search->location);
        elseif ($search->user->hasRole("ROLE_LOCAL") || $search->user->hasRole("ROLE_LOGISTICS"))
            $qb = $qb->andWhere('IDENTITY(o.location) IN (:locationIds)')->setParameter('locationIds', $search->user->getLocationIds()); 

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Supplier $newSupplier
     * @return Supplier
     */
    public function checkExists(Supplier $newSupplier)
    {
        // First: strict comparision, loose result count

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->from("AppBundle:Supplier", "s")->select("s"); 
            
        if ($newSupplier->getName() && strlen($newSupplier->getName()) > 2) {
            $qb = $qb->orWhere("s.name = :name")->setParameter("name", $newSupplier->getName());
        }

        if ($newSupplier->getEmail() && strlen($newSupplier->getEmail()) > 5) {
            $qb = $qb->orWhere("s.email = :email")->setParameter("email", $newSupplier->getEmail());
        }

        $result = $qb->getQuery()->getResult();

        if (count($result) > 0)
        {
            $this->_em->detach($newSupplier);
            $newSupplier = null;
            return $result[0];
        }
        else
        {
            // Second: loose comparision, strict result count

            $qb = $this->getEntityManager()->createQueryBuilder()
                ->from("AppBundle:Supplier", "s")->select("s"); 
            
            if ($newSupplier->getName() && strlen($newSupplier->getName()) > 2) {
                $qb = $qb->orWhere("SOUNDEX(s.name) like SOUNDEX(:name)")->setParameter("name", $newSupplier->getName());
            }

            if ($newSupplier->getPhone() && strlen($newSupplier->getPhone()) > 5) {
                $qb = $qb->orWhere("REPLACE(s.phone, '-', '') = :phone")->setParameter("phone", str_replace($newSupplier->getPhone(), "-", ""));
                $qb = $qb->orWhere("REPLACE(s.phone2, '-', '') = :phone")->setParameter("phone", str_replace($newSupplier->getPhone(), "-", ""));
            }

            $result = $qb->getQuery()->getResult();

            if (count($result) == 1)
            {
                $this->_em->detach($newSupplier);
                $newSupplier = null;
                return $result[0];
            }
            else
            {
                return $newSupplier;
            }
        }
    }
}
