# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.menubuilder:
        class: AppBundle\Menu\Builder
<<<<<<< HEAD
    productController:
        class: TrackBundle\Controller\ProductController
        arguments:
          $em: '@doctrine.orm.entity_manager'
=======
    on_request_listener:
        class: TrackBundle\Filter\OnRequestListener
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
>>>>>>> 0646e40759d39b397190db9ff3785e91fbe7a0f3
